# Generated by Django 4.2 on 2023-05-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_title_todo_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='person',
            new_name='title',
        ),
    ]
